django-master/01_django/articles/urls.py
from django.urls import path
# 명시적 상대경로
from . import views


app_name = 'articles'
urlpatterns = [
    path('index/', views.index, name='index'),
    path('greeting/', views.greeting, name='greeting'),
    path('dinner/', views.dinner, name='dinner'),
    path('throw/', views.throw, name='throw'),
    path('catch/', views.catch, name='catch'),
    path('hello/<str:name>/', views.hello, name='hello'),
]

django-master/01_django/firstpjt/urls.py
from django.contrib import admin
from django.urls import path, include
from articles import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('pages/', include('pages.urls')),
]

django-master/01_django/pages/urls.py
from django.urls import path
# 명시적 상대경로
from . import views

# 당장 path를 쓰지 않더라도 urlpatterns는 작성해야 함
app_name = 'pages'
urlpatterns = [
    path('index/', views.index, name='index'),
]

django-master/01_django/articles/models.py
from django.db import models

# Create your models here.

django-master/01_django/pages/models.py
from django.db import models

# Create your models here.

django-master/01_django/articles/views.py
import random
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'articles/index.html')


def greeting(request):
    foods = ['apple', 'banana', 'coconut',]
    info = {
        'name': 'Alice',
    }
    context = {
        'info': info,
        'foods': foods,
    }
    return render(request, 'articles/greeting.html', context)


def dinner(request):
    foods = ['apple', 'banana', 'coconut',]
    pick = random.choice(foods)
    context = {
        'pick': pick,
        'foods': foods,
    }
    return render(request, 'articles/dinner.html', context)


def throw(request):
    return render(request, 'articles/throw.html')


def catch(request):
    # throw에서 보낸 데이터를 찾아서 저장
    # print(request)
    # print(type(request))
    # print(request.GET)
    # print(request.GET.get('message'))
    message = request.GET.get('message')
    context = {
        'message': message,
    }
    return render(request, 'articles/catch.html', context)


def hello(request, name):
    context = {
        'name': name,
    }
    return render(request, 'articles/hello.html', context)

django-master/01_django/pages/views.py
from pydoc import render_doc
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'pages/index.html')

django-master/01_django/articles/templates/articles/catch.html
{% extends 'base.html' %}

{% block content %}
  <h1>Catch</h1>
  <h2>여기서 {{ message }}를 받았다!!</h2>
  <a href="{% url 'articles:throw' %}">다시 던지러!</a>
{% endblock content %}

django-master/01_django/articles/templates/articles/dinner.html
{% extends 'base.html' %}

{% block content %}
  <p>{{ pick }}는 {{ pick|length }}글자입니다.</p>
  <p>{{ foods|join:", " }}</p>

  <p>메뉴판</p>
  <ul>
    {% for food in foods %}
      <li>{{ food }}</li>
    {% endfor %}
  </ul>

  {% comment %} 
    <p>주석</p>
    <h2>여러 줄 주석</h2>
  {% endcomment %}
  <a href="{% url 'articles:index' %}">뒤로가기</a>
{% endblock content %}

django-master/01_django/articles/templates/articles/greeting.html
{% extends 'base.html' %}

{% block content %}
  <h1>안녕하세요 {{ info.name }} 입니다.</h1>
  <p>저는 {{ foods.0 }}를 가장 좋아합니다.</p>

  <a href="{% url 'articles:index' %}">뒤로가기</a>
{% endblock content %}

django-master/01_django/articles/templates/articles/hello.html
{% extends 'base.html' %}

{% block content %}
  <h1>Hello</h1>
  <h2>만나서 반가워요 ! {{ name }}님!</h2>
{% endblock content %}

django-master/01_django/articles/templates/articles/index.html
{% extends 'base.html' %}

{% block content %}
  <h1>만나서 반갑습니다!!</h1>
  <a href="{% url 'articles:greeting' %}">greeting</a>
  <a href="{% url 'articles:dinner' %}">dinner</a>
  <a href="{% url 'articles:throw' %}">throw</a>
  <a href="{% url 'pages:index' %}">두번째 앱의 인덱스로 고고!</a>
{% endblock content %}

django-master/01_django/articles/templates/articles/throw.html
{% extends 'base.html' %}

{% block content %}
  <h1>Throw</h1>
  <form action="{% url 'articles:catch' %}" method="GET">
    <label for="message">Throw</label>
    <input type="text" name="message" id="message">
    <input type="submit">
  </form>
  <a href="{% url 'articles:index' %}">뒤로가기</a>
{% endblock content %}

django-master/01_django/pages/templates/pages/index.html
{% extends 'base.html' %}


{% block content %}
  <h1>두번째 앱의 인덱스 페이지!</h1>
{% endblock content %}

django-master/01_django/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
  </head>
  <body>
    {% block content %}
    {% endblock content %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
  </body>
</html>