django-master/02_django/articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'
urlpatterns = [
    path('', views.index, name='index'),
    path('new/', views.new, name='new'),
    path('create/', views.create, name='create'),
    path("<int:pk>/", views.detail, name="detail"),
    path("<int:pk>/delete/", views.delete, name="delete"),
    path("<int:pk>/edit/", views.edit, name="edit"),
    path("<int:pk>/update/", views.update, name="update"),
]

django-master/02_django/crud/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
]

django-master/02_django/articles/models.py
from django.db import models

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=10)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

django-master/02_django/articles/views.py
from django.shortcuts import render, redirect # redirect 도 추가
from .models import Article


# Create your views here.
def index(request):
    # DB에 전체 데이터를 조회
    articles = Article.objects.all()
    context = {
        'articles': articles,
    }
    return render(request, 'articles/index.html', context)


def new(request):
    return render(request, 'articles/new.html')


def create(request):
    # 사용자의 데이터를 받아서
    title = request.POST.get('title')
    content = request.POST.get('content')

    # DB에 저장
    # 1
    # article = Article()
    # article.title = title
    # article.content = content
    # article.save()

    # 2
    article = Article(title=title, content=content)
    article.save()

    # 3
    # Article.objects.create(title=title, content=content)

    # return render(request, 'articles/index.html')
    # return redirect("articles:index")
    return redirect("articles:detail", article.pk)

def detail(request, pk):
    article = Article.objects.get(pk=pk)
    context = {
        "article" : article,
    }
    return render(request, "articles/detail.html", context)

def delete(request, pk):
    article = Article.objects.get(pk=pk)
    article.delete()
    return redirect("articles:index")

def edit(request, pk):
    article = Article.objects.get(pk=pk)
    context = {"article" : article}
    return render(request, "articles/edit.html", context)

def update(request, pk):
    article = Article.objects.get(pk=pk)
    article.title = request.POST.get("title")
    article.content = request.POST.get("content")
    article.save()
    return redirect("articles:detail", article.pk)

django-master/02_django/articles/templates/articles/create.html
{% extends 'base.html' %}

{% block content %}
  <h1>Create</h1>
  <p>게시글이 잘 작성되었습니다.</p>
  <a href="{% url 'articles:index' %}">뒤로가기</a>
{% endblock content %}

django-master/02_django/articles/templates/articles/detail.html
{% extends 'base.html' %}

{% block content %}
    <h2>DETAIL</h2>
    <h3>{{ article.pk }} 번째 글</h3>
    <hr>
    <p>제목 : {{ article.title }}</p>
    <p>내용 : {{ article.content }}</p>
    <p>작성 시각 : {{ article.created_at }}</p>
    <p>수정 시각 : {{ article.created_at }}</p>
    <hr>
    <a href="{% url "articles:edit" article.pk %}">[edit]</a>
    <form action="{% url "articles:delete" article.pk %}" method="POST">
    {% csrf_token %}
    <input type="submit" value="DELETE">
    </form>
    <a href="{% url "articles:index" %}">[back]</a>
    <a href="{% url "articles:detail" article.pk|add:-1 %}">[이전]</a>
    <a href="{% url "articles:detail" article.pk|add:+1 %}">[다음]</a>
{% endblock content %}

django-master/02_django/articles/templates/articles/edit.html
{% extends 'base.html' %}

{% block content %}
    <h1>EDIT</h1>
    <form action="{% url "articles:update" article.pk %}" method="POST">
        {% csrf_token %}
        <label for="title">Title :</label>
        <input id="title" type="text" name="title" value="{{article.title}}"><br>
        <label for="content">Content :
        </label>
        <textarea name="content" id="content" cols="30" rows="5">
            {{article.content}}
        </textarea>
        <input type="submit">
    </form>
    <a href="{% url "articles:index" %}">[back]</a>
{% endblock content %}

django-master/02_django/articles/templates/articles/index.html
{% extends 'base.html' %}

{% block content %}
  <h1>Articles</h1>
  <a href="{% url 'articles:new' %}">NEW</a>
  <hr>
  {% for article in articles %}
    <p>글 번호 : {{ article.pk }}</p>
    <p>제목 : {{ article.title }}</p>
    <p>내용 : {{ article.content }}</p>
    <a href="{% url "articles:detail" article.pk %}">[detail]</a>
    <hr>
  {% endfor %}
{% endblock content %}

django-master/02_django/articles/templates/articles/new.html
{% extends 'base.html' %}

{% block content %}
  <h1>NEW</h1>
  <form action="{% url 'articles:create' %}" method="POST">
    {% csrf_token %}
    <label for="title">Title: </label>
    <input type="text" name="title" id="title"><br>
    <label for="content">Content: </label>
    <input type="text" name="content" id="content"><br>
    <input type="submit">
  </form>
  <hr>
  <a href="{% url 'articles:index' %}">뒤로가기</a>
{% endblock content %}

django-master/02_django/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
  <title>Document</title>
</head>
<body>
  <div class="container">
    {% block content %}
    {% endblock content %}
  </div>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
</body>
</html>